=== huntermlady/Audible/shared/schemas/team.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://huntermlady.github.io/Audible/schemas/team.schema.json",
  "title": "Team",
  "description": "One team in shared/teams.json (an array of these). Abbreviations are nflverse's.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "abbr",
    "name",
    "nickname",
    "conference",
    "division",
    "color_primary",
    "color_secondary",
    "logo",
    "logo_url",
    "wordmark_url"
  ],
  "properties": {
    "abbr": {
      "type": "string",
      "pattern": "^[A-Z]{2,3}$"
    },
    "name": {
      "type": "string"
    },
    "nickname": {
      "type": "string"
    },
    "conference": {
      "type": "string",
      "enum": [
        "AFC",
        "NFC"
      ]
    },
    "division": {
      "type": "string",
      "enum": [
        "AFC East",
        "AFC North",
        "AFC South",
        "AFC West",
        "NFC East",
        "NFC North",
        "NFC South",
        "NFC West"
      ]
    },
    "color_primary": {
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "color_secondary": {
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "logo": {
      "type": [
        "string",
        "null"
      ]
    },
    "logo_url": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "pattern": "^https://",
      "description": "Team logo (nflverse team_logo_espn), hotlinked; never committed as a file."
    },
    "wordmark_url": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri",
      "pattern": "^https://",
      "description": "Team wordmark (nflverse team_wordmark), hotlinked."
    }
  }
}

=== huntermlady/Audible/shared/teams.json
[
  {
    "abbr": "ARI",
    "name": "Arizona Cardinals",
    "nickname": "Cardinals",
    "conference": "NFC",
    "division": "NFC West",
    "color_primary": "#97233F",
    "color_secondary": "#000000",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/ARI.png"
  },
  {
    "abbr": "ATL",
    "name": "Atlanta Falcons",
    "nickname": "Falcons",
    "conference": "NFC",
    "division": "NFC South",
    "color_primary": "#A71930",
    "color_secondary": "#000000",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/ATL.png"
  },
  {
    "abbr": "BAL",
    "name": "Baltimore Ravens",
    "nickname": "Ravens",
    "conference": "AFC",
    "division": "AFC North",
    "color_primary": "#241773",
    "color_secondary": "#9E7C0C",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/BAL.png"
  },
  {
    "abbr": "BUF",
    "name": "Buffalo Bills",
    "nickname": "Bills",
    "conference": "AFC",
    "division": "AFC East",
    "color_primary": "#00338D",
    "color_secondary": "#C60C30",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/BUF.png"
  },
  {
    "abbr": "CAR",
    "name": "Carolina Panthers",
    "nickname": "Panthers",
    "conference": "NFC",
    "division": "NFC South",
    "color_primary": "#0085CA",
    "color_secondary": "#101820",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500-dark/car.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/CAR.png"
  },
  {
    "abbr": "CHI",
    "name": "Chicago Bears",
    "nickname": "Bears",
    "conference": "NFC",
    "division": "NFC North",
    "color_primary": "#0B162A",
    "color_secondary": "#C83803",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/CHI.png"
  },
  {
    "abbr": "CIN",
    "name": "Cincinnati Bengals",
    "nickname": "Bengals",
    "conference": "AFC",
    "division": "AFC North",
    "color_primary": "#FB4F14",
    "color_secondary": "#000000",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/CIN.png"
  },
  {
    "abbr": "CLE",
    "name": "Cleveland Browns",
    "nickname": "Browns",
    "conference": "AFC",
    "division": "AFC North",
    "color_primary": "#311D00",
    "color_secondary": "#FF3C00",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/CLE.png"
  },
  {
    "abbr": "DAL",
    "name": "Dallas Cowboys",
    "nickname": "Cowboys",
    "conference": "NFC",
    "division": "NFC East",
    "color_primary": "#003594",
    "color_secondary": "#869397",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/DAL.png"
  },
  {
    "abbr": "DEN",
    "name": "Denver Broncos",
    "nickname": "Broncos",
    "conference": "AFC",
    "division": "AFC West",
    "color_primary": "#FB4F14",
    "color_secondary": "#002244",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/DEN.png"
  },
  {
    "abbr": "DET",
    "name": "Detroit Lions",
    "nickname": "Lions",
    "conference": "NFC",
    "division": "NFC North",
    "color_primary": "#0076B6",
    "color_secondary": "#B0B7BC",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/DET.png"
  },
  {
    "abbr": "GB",
    "name": "Green Bay Packers",
    "nickname": "Packers",
    "conference": "NFC",
    "division": "NFC North",
    "color_primary": "#203731",
    "color_secondary": "#FFB612",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/GB.png"
  },
  {
    "abbr": "HOU",
    "name": "Houston Texans",
    "nickname": "Texans",
    "conference": "AFC",
    "division": "AFC South",
    "color_primary": "#03202F",
    "color_secondary": "#A71930",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/HOU.png"
  },
  {
    "abbr": "IND",
    "name": "Indianapolis Colts",
    "nickname": "Colts",
    "conference": "AFC",
    "division": "AFC South",
    "color_primary": "#002C5F",
    "color_secondary": "#A2AAAD",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/IND.png"
  },
  {
    "abbr": "JAX",
    "name": "Jacksonville Jaguars",
    "nickname": "Jaguars",
    "conference": "AFC",
    "division": "AFC South",
    "color_primary": "#006778",
    "color_secondary": "#D7A22A",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/JAX.png"
  },
  {
    "abbr": "KC",
    "name": "Kansas City Chiefs",
    "nickname": "Chiefs",
    "conference": "AFC",
    "division": "AFC West",
    "color_primary": "#E31837",
    "color_secondary": "#FFB81C",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/KC.png"
  },
  {
    "abbr": "LA",
    "name": "Los Angeles Rams",
    "nickname": "Rams",
    "conference": "NFC",
    "division": "NFC West",
    "color_primary": "#003594",
    "color_secondary": "#FFA300",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/LA.png"
  },
  {
    "abbr": "LAC",
    "name": "Los Angeles Chargers",
    "nickname": "Chargers",
    "conference": "AFC",
    "division": "AFC West",
    "color_primary": "#0080C6",
    "color_secondary": "#FFC20E",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/LAC.png"
  },
  {
    "abbr": "LV",
    "name": "Las Vegas Raiders",
    "nickname": "Raiders",
    "conference": "AFC",
    "division": "AFC West",
    "color_primary": "#000000",
    "color_secondary": "#A5ACAF",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/LV.png"
  },
  {
    "abbr": "MIA",
    "name": "Miami Dolphins",
    "nickname": "Dolphins",
    "conference": "AFC",
    "division": "AFC East",
    "color_primary": "#008E97",
    "color_secondary": "#FC4C02",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/MIA.png"
  },
  {
    "abbr": "MIN",
    "name": "Minnesota Vikings",
    "nickname": "Vikings",
    "conference": "NFC",
    "division": "NFC North",
    "color_primary": "#4F2683",
    "color_secondary": "#FFC62F",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/MIN.png"
  },
  {
    "abbr": "NE",
    "name": "New England Patriots",
    "nickname": "Patriots",
    "conference": "AFC",
    "division": "AFC East",
    "color_primary": "#002244",
    "color_secondary": "#C60C30",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/NE.png"
  },
  {
    "abbr": "NO",
    "name": "New Orleans Saints",
    "nickname": "Saints",
    "conference": "NFC",
    "division": "NFC South",
    "color_primary": "#D3BC8D",
    "color_secondary": "#101820",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/NO.png"
  },
  {
    "abbr": "NYG",
    "name": "New York Giants",
    "nickname": "Giants",
    "conference": "NFC",
    "division": "NFC East",
    "color_primary": "#0B2265",
    "color_secondary": "#A71930",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/NYG.png"
  },
  {
    "abbr": "NYJ",
    "name": "New York Jets",
    "nickname": "Jets",
    "conference": "AFC",
    "division": "AFC East",
    "color_primary": "#125740",
    "color_secondary": "#000000",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/NYJ.png"
  },
  {
    "abbr": "PHI",
    "name": "Philadelphia Eagles",
    "nickname": "Eagles",
    "conference": "NFC",
    "division": "NFC East",
    "color_primary": "#004C54",
    "color_secondary": "#A5ACAF",
    "logo": null,
    "logo_url": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    "wordmark_url": "https://github.com/nflverse/nflverse-pbp/raw/master/wordmarks/PHI.png"
